Support enforced strict mode
All (>50) modules that I use work fine with enforced strict mode.
The only exception is `errno`. This commit fixes that.

Steps to reproduce:
mkdir /tmp/a
cd /tmp/a
npm install errno
echo 'require("errno")' > w.js
node --use_strict w.js

/tmp/a/node_modules/errno/custom.js:18
    Error.captureStackTrace(this, arguments.callee)
                                           ^

TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them
    at Error.CustomError (/tmp/a/node_modules/errno/custom.js:18:44)
    at createError (/tmp/a/node_modules/errno/custom.js:42:43)
    at ce (/tmp/a/node_modules/errno/custom.js:48:12)
    at module.exports (/tmp/a/node_modules/errno/custom.js:52:25)
    at Object.<anonymous> (/tmp/a/node_modules/errno/errno.js:312:44)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)